# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "productbundle"
client_id = "e18fa917fa90c132ba197988cc8c3182"
application_url = "https://ethernet-maintains-coffee-ix.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_price_rules,write_discounts,read_content,write_content,write_orders,read_themes"

[auth]
redirect_urls = [
  "https://ethernet-maintains-coffee-ix.trycloudflare.com/auth/callback",
  "https://ethernet-maintains-coffee-ix.trycloudflare.com/auth/shopify/callback",
  "https://ethernet-maintains-coffee-ix.trycloudflare.com/api/auth/callback",
  "https://ethernet-maintains-coffee-ix.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "playgroundstoree.myshopify.com"
