# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d237800fbe8fb809677f692033b02ae"
application_url = "https://supplier-developers-recorded-flex.trycloudflare.com"
embedded = true
name = "latestBundle"
handle = "latestbundle"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pallavitesting.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_themes,write_content,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://supplier-developers-recorded-flex.trycloudflare.com/auth/callback",
  "https://supplier-developers-recorded-flex.trycloudflare.com/auth/shopify/callback",
  "https://supplier-developers-recorded-flex.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
