# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8c12ad6dd6cca8d5809e99013d4289b"
name = "Staging Advanced Bundles"
handle = "staging-advanced-bundles"
application_url = "https://includes-spending-fleet-charter.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "robins-store1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_themes,write_content,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://includes-spending-fleet-charter.trycloudflare.com/auth/callback",
  "https://includes-spending-fleet-charter.trycloudflare.com/auth/shopify/callback",
  "https://includes-spending-fleet-charter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
