# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f96a8c9db0ecb7d5f6b2191d28c602c"
name = "Smart Bundle Discounts"
handle = "smart-bundle-discounts-1"
application_url = "https://bundlesgroup.com/"
embedded = true

[auth]
redirect_urls = [
  "https://bundlesgroup.com/api/auth",
  "https://bundlesgroup.com/api/auth/callback"
]


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_themes,write_content,write_discounts,write_orders,write_price_rules,write_products"

[webhooks]
api_version = "2024-07"


[pos]
embedded = false
