# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d237800fbe8fb809677f692033b02ae"
name = "latestBundle"
handle = "latestbundle"
application_url = "https://offered-lowest-enforcement-baptist.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pallavitesting.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_themes,write_content,write_discounts,write_inventory,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://offered-lowest-enforcement-baptist.trycloudflare.com/auth/callback",
  "https://offered-lowest-enforcement-baptist.trycloudflare.com/auth/shopify/callback",
  "https://offered-lowest-enforcement-baptist.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
