# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1de23c3f91fb1f536754a875d8febf66"
name = "smartbundle"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_themes,write_content,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
