# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e13323374d92132ba17048d14e6ecb0e"
name = "akashbundlelive"
handle = "akashbundlelive"
application_url = "https://dsl-nylon-ships-some.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robins-store1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_themes,write_content,write_discounts,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://dsl-nylon-ships-some.trycloudflare.com/auth/callback",
  "https://dsl-nylon-ships-some.trycloudflare.com/auth/shopify/callback",
  "https://dsl-nylon-ships-some.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
