# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8c12ad6dd6cca8d5809e99013d4289b"
name = "Staging Advanced Bundles"
handle = "staging-advanced-bundles"
application_url = "https://madagascar-stars-tue-polo.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "robins-store1.myshopify.com"

[auth]
redirect_urls = [
  "https://madagascar-stars-tue-polo.trycloudflare.com/auth/callback",
  "https://madagascar-stars-tue-polo.trycloudflare.com/auth/shopify/callback",
  "https://madagascar-stars-tue-polo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
