
query CartInput {
  cart {
    lines {
      id
      quantity
      cost {
        subtotalAmount {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          product {
            id
          }
        }
      }
      UNIQUE_CODE: attribute(key: "_SD_BUNDLE_ID") {
        value
      }
    }
  }
  discount {
    discountClasses
  }
  shop {
    metafield(namespace: "$app:discount-function", key: "sd_bundles") {
      jsonValue
    }
  }
}
